/**
 * Generate apps/web/src/samples.generated.ts from rides/*.json + rides/metadata.json.
 *
 * This is the one piece of build-time data injection that survives. It is not
 * part of `npm run build`: the output is committed, and you only rerun it when
 * a sample ride or its metadata changes.
 *
 *   npm run samples
 */
import { readFileSync, writeFileSync } from 'node:fs';

const OUT = 'apps/web/src/samples.generated.ts';
const { rides } = JSON.parse(readFileSync('rides/metadata.json', 'utf8'));

const round = (values, dp) => values.map((v) => Number(v.toFixed(dp)));
const arr = (values) => `[${values.join(',')}]`;

const blocks = rides.map((meta) => {
  const raw = JSON.parse(readFileSync(`rides/${meta.file}.json`, 'utf8'));
  return [
    '  {',
    `    id: ${JSON.stringify(meta.file)},`,
    `    name: ${JSON.stringify(meta.name)},`,
    `    sub: ${JSON.stringify(meta.sub)},`,
    `    movingTime: ${meta.movingTime},`,
    `    ascent: ${meta.ascent},`,
    `    intro: ${JSON.stringify(meta.intro)},`,
    `    foot: ${JSON.stringify(meta.foot)},`,
    '    source: "sample",',
    '    samples: {',
    `      dist: ${arr(round(raw.distance, 0))},`,
    `      alt: ${arr(round(raw.altitude, 1))},`,
    `      hr: ${arr(raw.heart_rate.map((h) => (h == null ? 'null' : h)))},`,
    `      time: ${arr(raw.time)},`,
    '    },',
    '  },',
  ].join('\n');
});

const file = `// GENERATED by tools/pack-samples.js — do not edit by hand.
// Regenerate with: npm run samples
import type { RideMeta, RideSamples } from '@ascents/domain';

export interface SampleRide extends RideMeta {
  readonly samples: RideSamples;
}

/**
 * The six curated rides. They ship with the page so it has something to show
 * before anyone uploads anything, and so an uploaded ride can be compared
 * against the same peaks rather than sitting on its own.
 */
export const SAMPLE_RIDES: readonly SampleRide[] = [
${blocks.join('\n')}
];
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT} (${rides.length} rides, ${(file.length / 1024).toFixed(1)} KB)`);
